name: Driver health check

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get driver status
        uses: ./ci/get-driver-status
        with:
          host: https://dev.uniresolver.io
          out_folder: /github/workspace/driver-status-reports
          keep_result: true
      - name: Run did-test-suite
        run: |
          echo "Run did-test-suite for ${{ env.filename }}"